-- FEE_POLICY_CONFIGS dual-side fee policy columns
-- Safe to run multiple times.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'SHIPPER_LEVEL0_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (SHIPPER_LEVEL0_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'SHIPPER_LEVEL1_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (SHIPPER_LEVEL1_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'SHIPPER_LEVEL2_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (SHIPPER_LEVEL2_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'SHIPPER_LEVEL3_PLUS_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (SHIPPER_LEVEL3_PLUS_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'DRIVER_LEVEL0_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (DRIVER_LEVEL0_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'DRIVER_LEVEL1_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (DRIVER_LEVEL1_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'DRIVER_LEVEL2_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (DRIVER_LEVEL2_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'DRIVER_LEVEL3_PLUS_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (DRIVER_LEVEL3_PLUS_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'SHIPPER_FIRST_PAYMENT_PROMO_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (SHIPPER_FIRST_PAYMENT_PROMO_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'DRIVER_FIRST_TRANSPORT_PROMO_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (DRIVER_FIRST_TRANSPORT_PROMO_RATE NUMBER(10,4))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
       AND COLUMN_NAME = 'TOSS_RATE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE FEE_POLICY_CONFIGS ADD (TOSS_RATE NUMBER(10,4))';
    END IF;
END;
/

UPDATE FEE_POLICY_CONFIGS
   SET SHIPPER_LEVEL0_RATE = NVL(SHIPPER_LEVEL0_RATE, LEVEL0_RATE),
       SHIPPER_LEVEL1_RATE = NVL(SHIPPER_LEVEL1_RATE, LEVEL1_RATE),
       SHIPPER_LEVEL2_RATE = NVL(SHIPPER_LEVEL2_RATE, LEVEL2_RATE),
       SHIPPER_LEVEL3_PLUS_RATE = NVL(SHIPPER_LEVEL3_PLUS_RATE, LEVEL3_PLUS_RATE),
       DRIVER_LEVEL0_RATE = NVL(DRIVER_LEVEL0_RATE, 0.0250),
       DRIVER_LEVEL1_RATE = NVL(DRIVER_LEVEL1_RATE, 0.0200),
       DRIVER_LEVEL2_RATE = NVL(DRIVER_LEVEL2_RATE, 0.0180),
       DRIVER_LEVEL3_PLUS_RATE = NVL(DRIVER_LEVEL3_PLUS_RATE, 0.0150),
       SHIPPER_FIRST_PAYMENT_PROMO_RATE = NVL(SHIPPER_FIRST_PAYMENT_PROMO_RATE, FIRST_PAYMENT_PROMO_RATE),
       DRIVER_FIRST_TRANSPORT_PROMO_RATE = NVL(DRIVER_FIRST_TRANSPORT_PROMO_RATE, 0.0150),
       TOSS_RATE = NVL(TOSS_RATE, 0.0300)
 WHERE SHIPPER_LEVEL0_RATE IS NULL
    OR SHIPPER_LEVEL1_RATE IS NULL
    OR SHIPPER_LEVEL2_RATE IS NULL
    OR SHIPPER_LEVEL3_PLUS_RATE IS NULL
    OR DRIVER_LEVEL0_RATE IS NULL
    OR DRIVER_LEVEL1_RATE IS NULL
    OR DRIVER_LEVEL2_RATE IS NULL
    OR DRIVER_LEVEL3_PLUS_RATE IS NULL
    OR SHIPPER_FIRST_PAYMENT_PROMO_RATE IS NULL
    OR DRIVER_FIRST_TRANSPORT_PROMO_RATE IS NULL
    OR TOSS_RATE IS NULL;
COMMIT;

-- verify
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'FEE_POLICY_CONFIGS'
   AND COLUMN_NAME IN (
       'SHIPPER_LEVEL0_RATE',
       'SHIPPER_LEVEL1_RATE',
       'SHIPPER_LEVEL2_RATE',
       'SHIPPER_LEVEL3_PLUS_RATE',
       'DRIVER_LEVEL0_RATE',
       'DRIVER_LEVEL1_RATE',
       'DRIVER_LEVEL2_RATE',
       'DRIVER_LEVEL3_PLUS_RATE',
       'SHIPPER_FIRST_PAYMENT_PROMO_RATE',
       'DRIVER_FIRST_TRANSPORT_PROMO_RATE',
       'TOSS_RATE'
   )
 ORDER BY COLUMN_NAME;
