-- PAYMENT_GATEWAY_TRANSACTIONS retry queue columns
-- Safe to run multiple times.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
       AND COLUMN_NAME = 'RETRY_COUNT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_GATEWAY_TRANSACTIONS ADD (RETRY_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
       AND COLUMN_NAME = 'LAST_RETRY_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_GATEWAY_TRANSACTIONS ADD (LAST_RETRY_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
       AND COLUMN_NAME = 'NEXT_RETRY_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_GATEWAY_TRANSACTIONS ADD (NEXT_RETRY_AT TIMESTAMP(6))';
    END IF;
END;
/

UPDATE PAYMENT_GATEWAY_TRANSACTIONS
   SET RETRY_COUNT = 0
 WHERE RETRY_COUNT IS NULL;
COMMIT;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_PGTX_NEXT_RETRY_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_PGTX_NEXT_RETRY_AT ON PAYMENT_GATEWAY_TRANSACTIONS (NEXT_RETRY_AT)';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_PGTX_EXPIRES_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_PGTX_EXPIRES_AT ON PAYMENT_GATEWAY_TRANSACTIONS (EXPIRES_AT)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TRANSPORT_PAYMENTS'
       AND COLUMN_NAME = 'PAYMENT_TIMING';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TRANSPORT_PAYMENTS ADD (PAYMENT_TIMING VARCHAR2(20 CHAR))';
    END IF;
END;
/

-- verify
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
   AND COLUMN_NAME IN ('RETRY_COUNT', 'LAST_RETRY_AT', 'NEXT_RETRY_AT')
 ORDER BY COLUMN_NAME;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'TRANSPORT_PAYMENTS'
   AND COLUMN_NAME = 'PAYMENT_TIMING';
