-- Purpose:
-- 1) Allow multiple PREPARED rows with PAYMENT_KEY NULL
-- 2) Keep uniqueness when PAYMENT_KEY is NOT NULL
-- 3) Keep lookup index for (PROVIDER, PAYMENT_KEY)

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
       AND CONSTRAINT_NAME = 'UK_PGTX_PROVIDER_PAYMENT_KEY';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_GATEWAY_TRANSACTIONS DROP CONSTRAINT UK_PGTX_PROVIDER_PAYMENT_KEY';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_PGTX_PROVIDER_PAYMENT_KEY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_PGTX_PROVIDER_PAYMENT_KEY ON PAYMENT_GATEWAY_TRANSACTIONS (PROVIDER, PAYMENT_KEY)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'UKX_PGTX_PROVIDER_PAYMENT_KEY_NN';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE UNIQUE INDEX UKX_PGTX_PROVIDER_PAYMENT_KEY_NN
              ON PAYMENT_GATEWAY_TRANSACTIONS (
                CASE WHEN PAYMENT_KEY IS NOT NULL THEN PROVIDER END,
                CASE WHEN PAYMENT_KEY IS NOT NULL THEN PAYMENT_KEY END
              )';
    END IF;
END;
/

-- verify
SELECT INDEX_NAME, UNIQUENESS
  FROM USER_INDEXES
 WHERE TABLE_NAME = 'PAYMENT_GATEWAY_TRANSACTIONS'
   AND INDEX_NAME IN ('IDX_PGTX_PROVIDER_PAYMENT_KEY', 'UKX_PGTX_PROVIDER_PAYMENT_KEY_NN');
